version: "3.8"
services:
  backend:
    build: .
    image: robera1/musicapi:v1
    container_name: backend
    ports:
      - "3005:3005"
    env_file:
      - ./.env
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
